leftnav:
- identifier: f2d7a10a-6265-a186-18e1-cff877b296c4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: cf40725a-580a-35e6-9d3b-1f4b14cdfbe8
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: e31ddbff-1ff0-3bfb-0353-d7cdba211ac2
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 12018fc7-cbee-1908-68cf-f8d44ce5a9fb
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 22db172d-a8de-592f-c86c-3df524c597d7
  name: Projects
  pageRef: /pages/projects
  weight: 50
